import pandas as pd

from config import (
    EXPERIMENT_REPORT_CSV_PATH,
    EXPERIMENT_REPORT_MARKDOWN_PATH,
    EXPERIMENT_RESULTS_PATH,
    RESULTS_DIR,
)


REQUIRED_COLUMNS = [
    "vectorizer",
    "model",
    "k",

    "validation_accuracy_mean",
    "validation_precision_macro_mean",
    "validation_recall_macro_mean",
    "validation_f1_macro_mean",
    "validation_f1_weighted_mean",

    "validation_precision_hate_speech_mean",
    "validation_recall_hate_speech_mean",
    "validation_f1_hate_speech_mean",

    "validation_precision_offensive_language_mean",
    "validation_recall_offensive_language_mean",
    "validation_f1_offensive_language_mean",

    "validation_precision_neither_mean",
    "validation_recall_neither_mean",
    "validation_f1_neither_mean",

    "train_f1_macro_mean",
]


def load_experiment_results() -> pd.DataFrame:
    """
    Loads the experiment results generated by main.py.
    """

    if not EXPERIMENT_RESULTS_PATH.exists():
        raise FileNotFoundError(
            f"Experiment results file was not found at: {EXPERIMENT_RESULTS_PATH}\n"
            "Run the experiments first with:\n"
            "python main.py"
        )

    return pd.read_csv(EXPERIMENT_RESULTS_PATH)


def validate_report_columns(results_df: pd.DataFrame) -> None:
    """
    Checks whether experiment_results.csv contains all columns required for the report.
    """

    missing_columns = [
        column for column in REQUIRED_COLUMNS
        if column not in results_df.columns
    ]

    if missing_columns:
        raise ValueError(
            "The experiment results file does not contain the new per-class metrics.\n"
            "You probably need to rerun the experiments with:\n"
            "python main.py\n\n"
            f"Missing columns: {missing_columns}"
        )


def create_report_table(results_df: pd.DataFrame) -> pd.DataFrame:
    """
    Creates one clean report table containing all experiments and key metrics.
    """

    validate_report_columns(results_df)

    report_df = results_df.copy()

    report_df["f1_macro_gap"] = (
        report_df["train_f1_macro_mean"]
        - report_df["validation_f1_macro_mean"]
    )

    selected_columns = [
        "vectorizer",
        "model",
        "k",

        "validation_accuracy_mean",
        "validation_precision_macro_mean",
        "validation_recall_macro_mean",
        "validation_f1_macro_mean",
        "validation_f1_weighted_mean",

        "validation_precision_hate_speech_mean",
        "validation_recall_hate_speech_mean",
        "validation_f1_hate_speech_mean",

        "validation_precision_offensive_language_mean",
        "validation_recall_offensive_language_mean",
        "validation_f1_offensive_language_mean",

        "validation_precision_neither_mean",
        "validation_recall_neither_mean",
        "validation_f1_neither_mean",

        "train_f1_macro_mean",
        "f1_macro_gap",
    ]

    report_df = report_df[selected_columns]

    renamed_columns = {
        "vectorizer": "Vectorizer",
        "model": "Model",
        "k": "K",

        "validation_accuracy_mean": "Accuracy",
        "validation_precision_macro_mean": "Precision Macro",
        "validation_recall_macro_mean": "Recall Macro",
        "validation_f1_macro_mean": "F1 Macro",
        "validation_f1_weighted_mean": "F1 Weighted",

        "validation_precision_hate_speech_mean": "Hate Precision",
        "validation_recall_hate_speech_mean": "Hate Recall",
        "validation_f1_hate_speech_mean": "Hate F1",

        "validation_precision_offensive_language_mean": "Offensive Precision",
        "validation_recall_offensive_language_mean": "Offensive Recall",
        "validation_f1_offensive_language_mean": "Offensive F1",

        "validation_precision_neither_mean": "Neither Precision",
        "validation_recall_neither_mean": "Neither Recall",
        "validation_f1_neither_mean": "Neither F1",

        "train_f1_macro_mean": "Train F1 Macro",
        "f1_macro_gap": "F1 Gap",
    }

    report_df = report_df.rename(columns=renamed_columns)

    numeric_columns = [
        "Accuracy",
        "Precision Macro",
        "Recall Macro",
        "F1 Macro",
        "F1 Weighted",

        "Hate Precision",
        "Hate Recall",
        "Hate F1",

        "Offensive Precision",
        "Offensive Recall",
        "Offensive F1",

        "Neither Precision",
        "Neither Recall",
        "Neither F1",

        "Train F1 Macro",
        "F1 Gap",
    ]

    report_df[numeric_columns] = report_df[numeric_columns].round(4)

    report_df = report_df.sort_values(
        by="F1 Macro",
        ascending=False
    ).reset_index(drop=True)

    return report_df


def save_report_csv(report_df: pd.DataFrame) -> None:
    """
    Saves the report table as CSV.
    """

    RESULTS_DIR.mkdir(exist_ok=True)

    report_df.to_csv(EXPERIMENT_REPORT_CSV_PATH, index=False)

    print("\nCSV report saved to:")
    print(EXPERIMENT_REPORT_CSV_PATH)


def save_report_markdown(report_df: pd.DataFrame) -> None:
    """
    Saves the report table as a Markdown file.
    """

    RESULTS_DIR.mkdir(exist_ok=True)

    markdown_table = report_df.to_markdown(index=False)

    report_text = f"""# Experiment Results Report

This table contains all machine learning experiments for the hate speech detection project.

The experiments compare:

- Bag of Words and TF-IDF text representations
- Naive Bayes, Logistic Regression and Random Forest classifiers
- Stratified K-Fold Cross-validation with k = 3, 5 and 10

The table is sorted by **F1 Macro** in descending order.

## Important note about class metrics

For each class, the report includes:

- Precision
- Recall
- F1-score

The most direct metric for answering "how much the model recognizes from each class" is **Recall**.

For example:

- **Hate Recall** shows how many of the real hate_speech examples were correctly detected.
- **Offensive Recall** shows how many of the real offensive_language examples were correctly detected.
- **Neither Recall** shows how many of the real neither examples were correctly detected.

{markdown_table}
"""

    with open(EXPERIMENT_REPORT_MARKDOWN_PATH, "w", encoding="utf-8") as file:
        file.write(report_text)

    print("\nMarkdown report saved to:")
    print(EXPERIMENT_REPORT_MARKDOWN_PATH)


def print_report_preview(report_df: pd.DataFrame, rows: int = 18) -> None:
    """
    Prints the report table in the terminal.
    """

    print("\n==============================")
    print("EXPERIMENT REPORT")
    print("==============================")

    print(report_df.head(rows).to_string(index=False))


def main() -> None:
    """
    Main function for generating the experiment report.
    """

    print("Loading experiment results...")

    results_df = load_experiment_results()

    report_df = create_report_table(results_df)

    save_report_csv(report_df)
    save_report_markdown(report_df)

    print_report_preview(report_df)

    print("\nReport generation completed successfully.")


if __name__ == "__main__":
    main()